"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:06:46.579526
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_departments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('erp_purchase_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_purchase_requests_code'), 'erp_purchase_requests', ['code'], unique=True)
    op.create_index(op.f('ix_erp_purchase_requests_status'), 'erp_purchase_requests', ['status'], unique=False)
    op.create_table('erp_stock_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_stock_items_name'), 'erp_stock_items', ['name'], unique=False)
    op.create_index(op.f('ix_erp_stock_items_sku'), 'erp_stock_items', ['sku'], unique=True)
    op.create_index(op.f('ix_erp_stock_items_status'), 'erp_stock_items', ['status'], unique=False)
    op.create_table('erp_employees',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department'], ['erp_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_employees_department'), 'erp_employees', ['department'], unique=False)
    op.create_index(op.f('ix_erp_employees_username'), 'erp_employees', ['username'], unique=True)
    op.create_table('erp_inventory_transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stock_item_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['erp_stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_inventory_transactions_stock_item_id'), 'erp_inventory_transactions', ['stock_item_id'], unique=False)
    op.create_table('erp_purchase_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('pr_id', sa.String(length=64), nullable=False),
    sa.Column('supplier', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['erp_purchase_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_purchase_orders_po_number'), 'erp_purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_erp_purchase_orders_pr_id'), 'erp_purchase_orders', ['pr_id'], unique=False)
    op.create_index(op.f('ix_erp_purchase_orders_status'), 'erp_purchase_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_purchase_orders_status'), table_name='erp_purchase_orders')
    op.drop_index(op.f('ix_erp_purchase_orders_pr_id'), table_name='erp_purchase_orders')
    op.drop_index(op.f('ix_erp_purchase_orders_po_number'), table_name='erp_purchase_orders')
    op.drop_table('erp_purchase_orders')
    op.drop_index(op.f('ix_erp_inventory_transactions_stock_item_id'), table_name='erp_inventory_transactions')
    op.drop_table('erp_inventory_transactions')
    op.drop_index(op.f('ix_erp_employees_username'), table_name='erp_employees')
    op.drop_index(op.f('ix_erp_employees_department'), table_name='erp_employees')
    op.drop_table('erp_employees')
    op.drop_index(op.f('ix_erp_stock_items_status'), table_name='erp_stock_items')
    op.drop_index(op.f('ix_erp_stock_items_sku'), table_name='erp_stock_items')
    op.drop_index(op.f('ix_erp_stock_items_name'), table_name='erp_stock_items')
    op.drop_table('erp_stock_items')
    op.drop_index(op.f('ix_erp_purchase_requests_status'), table_name='erp_purchase_requests')
    op.drop_index(op.f('ix_erp_purchase_requests_code'), table_name='erp_purchase_requests')
    op.drop_table('erp_purchase_requests')
    op.drop_table('erp_departments')
    # ### end Alembic commands ###
